#!/bin/bash
set -e
domfile=doms        # Path to file containing domain names per line
dkeyfile=dom.key    # Path to a private key file (to be created)
csrfile=dom.csr     # Path to the CSR file (to be created)
openssl genrsa 4096 > "$dkeyfile"
CN=`head -1 "$domfile"`
subjectAltName=`sed -e '/^[[:blank:]]*$/d' \
    -e 's/^[[:blank:]]*//' \
    -e 's/[[:blank:]]*$//' \
    -e 's/^/DNS:/' "$domfile" |
    tr '\n' ','`
subjectAltName="${subjectAltName/%,/}"

country_code=''     # Put two character country code
state=''            # Put state name
locality=''         # Put city name
org=''              # Put organization name
org_unit=''         # Put organization unit name
email=''            # Put email address

openssl req -new -sha256 -key "$dkeyfile" -subj "/CN=$CN/O=$org/OU=$org_unit/C=$country_code/ST=$state/L=$locality/emailAddress=$email" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf  <(printf "[SAN]\nsubjectAltName=$subjectAltName")) -out "$csrfile"
